# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(934, 689)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.camera_view = QtWidgets.QGraphicsView(self.centralwidget)
        self.camera_view.setObjectName("camera_view")
        self.verticalLayout_5.addWidget(self.camera_view)
        self.predict_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.predict_button.setFont(font)
        self.predict_button.setObjectName("predict_button")
        self.verticalLayout_5.addWidget(self.predict_button)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.products_list = QtWidgets.QListWidget(self.centralwidget)
        self.products_list.setObjectName("products_list")
        self.verticalLayout_6.addWidget(self.products_list)
        self.weights_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.weights_label.setFont(font)
        self.weights_label.setObjectName("weights_label")
        self.verticalLayout_6.addWidget(self.weights_label)
        self.receipt_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.receipt_button.setFont(font)
        self.receipt_button.setObjectName("receipt_button")
        self.verticalLayout_6.addWidget(self.receipt_button)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.predict_button.setText(_translate("MainWindow", "Определить товар"))
        self.weights_label.setText(_translate("MainWindow", "Вес товара: 0 кг"))
        self.receipt_button.setText(_translate("MainWindow", "Печать чека"))
